# Copyright (C) 2026 Eclipse Foundation and others.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: 2026 Eclipse Foundation
# SPDX-License-Identifier: EPL-2.0

# The workflow below serves to illustrate how tsffer and tsflink GitHub actions can be used in CI pipelines
# to automate the process of collecing TSF evidence, linking it into an existing TSF argument, and performing
# the scoring and report generation as part of a release flow.

---
# .github/workflows/release.yml
name: Release workflow

on:
  push:
    tags:
      - v*

concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  quality_artifacts:
    name: Collect quality artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v6

      # Add README evidence item
      - name: Upload README to release
        uses: svenstaro/upload-release-action@v2
        id: upload_README
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: README.md
          tag: ${{ github.ref }}
      - name: tsffer README evidence
        uses: AnotherDaniel/tsffer@v0.5.5
        id: tsffer_README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: reference
          reference_properties: |
            {
              "reference_type": "download_url",
              "url": "${{ steps.upload_README.outputs.browser_download_url }}"
            }
          asset_description: "The tsftest README file"
          asset_name: "Project README"
          asset_tsf_ids: "TSFTEST-PROJECT_README,TSFTEST-PROJECT_SCOPE"

      # Add an OFT requirements item
      - name: tsffer README evidence
        uses: AnotherDaniel/tsffer@v0.5.5
        id: tsffer_requirement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: reference
          reference_properties: |
            {
              "reference_type": "openfasttrace",
              "requirement_id": "req-test",
              "file_patterns": "trustable/*.md"
            }
          asset_description: "Tracing info for an OpenFastTrace requirement"
          asset_name: "OpenFastTrace Requirement"
          asset_tsf_ids: "TSFTEST-PROJECT_README"

  trustable_scoring:
    # This only runs if this workflow is initiated via a tag-push with pattern 'v*'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Package and score tsf artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    needs:
      - quality_artifacts
    steps:
      - uses: actions/checkout@v6

      - name: Package tsffer snippets and add to release artifacts
        uses: AnotherDaniel/tsffer@v0.5.5
        id: package_tsffer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: package
          release_upload: true

      - name: Link, score and publish TSF tree
        uses: AnotherDaniel/tsflink@v0.1.6
        id: link_tsffer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload TSF report to release artifacts
        uses: svenstaro/upload-release-action@v2
        id: upload_TSF_report
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.link_tsffer.outputs.trudag_report }}
          tag: ${{ github.ref }}
      - name: Print TSF score
        run: echo "TSF score is ${{ steps.link_tsffer.outputs.trudag_score }}"
